version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    user: "${UID}:${GID}"
    environment:
      - PORT=5000
    depends_on:
      - db
    networks:
      - web_devops

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    user: "${UID}:${GID}"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    networks:
      - web_devops

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - web_devops

volumes:
  db_data:

networks:
  web_devops:
